### PR TITLE
Beam weapon dev

### PR DESCRIPTION
**Pull request by BasilChristofis**
The Beam weapon has been developed, and so has a Bean weapon.
To test, please put the beam and bean weapons in the main scene from the prefab folder.

- [ ] Standards for code have been met.
- [ ] Game Balance aintained by weapons.
- [ ] No Accidental code changes occured,
- [ ] Beam Weapon shoots from player to a set range.
- [ ] Bean Weapon shoots at a high fire rate, at 1 damage,

### CODE REVIEW

**Comment by LachlanMcCaskill** [comment]
A couple of questions to start:

Can the beam weapon have it's range modified in the inspector? (I couldn't see any value for "range")

I honestly think it's better to have no sounds than the constant buzzing of the beam weapon, but that's something we can change when we go to add new audio. (Same with the bean weapon)

I actually really like the bean weapon better so far and it only needs some new sprites before I think we can put it in. (might need a slight change to the sound, but it actually sounds ok)

Also I had to just place the items in the scene to test them. It worked but it might be good to put that in the pull request description. Something like "To test: open the main scene and place the item in from the prefabs folder" might help with this.

**Comment by BasilChristofis** [comment]
Currently the range can't be edited from inspector,
Sound is default projectile sounds, due to copying default bullet for initial development. Same for bean weapon.
Sugestion for edit has been noted, and applied.
Thank you Lachlan.

**Comment by BasilChristofis** [comment]
Merged main into branch to resolve merge conflicts before branch gets pulled. Also, accidently muted my unity a while ago, so the lightsaber beam noises were unintentional.

**Comment by JarrydWorland** [comment]
We'll need to hold off on merging this for now until new sprites and assets can be developed including:

- Bean Weapon Projectile
- Beam/Default Weapon Icon differential 
- Beam Weapon Sounds (especially the starting one, not fun with headphones on :( )

I wasn't able to see the bean weapon inside of gameplay testing, has this been directly implemented into the main game yet or was this in a separate scene environment? 

Also a likely bug that doesn't reset fire rate value of default weapon when respawning from death

From an accessibility point of view, we're going to need a new name for the 'bean' weapon as it's too close to beam, very confusing with devs, double confusing from new players

**Comment by BasilChristofis** [comment]
image
Bean Weapon was deselected.
image
This needs to be ticked for it to appear. It is to be put in Gameplay, otherwise it randomly spawns when activated. I did not notice the glitch, and perhaps Seed Sprayer might work as an alternate of bean weapon?
BeanWeapn will also need an asset, as it currently looks like this:
 
image

**Comment by BasilChristofis** [comment]
No bug, just a fire rate difference between main and Beam Weapon Dev branch
Main Default value:
image
BWD Value:
image
I will be changing BWD to the correct value. Thank you for pointing out the Issue, Jarryd.

**Comment by BasilChristofis** [comment]
fixed

**Comment by JarrydWorland** [comment]
Game Design has obsolesced this component for the game - Closed PR

**Pull request closed without merging**
