### PR TITLE
Health aura particle

### PR DESCRIPTION
**Pull request by BasilChristofis**
On health increase, an aura is generated that indicates player healing.

Please check it works, no issues with other sprites, and it matches the general idea of what it's supposed to look like.

### CODE REVIEW

**Comment by LachlanMcCaskill** [comment]
Okay, the effect is a bit subtle.

Another thing, if this effect plays during lifesteal, why doesn't it play when the character is healed by other sources? It seems to me that we might need a "healing particle" to play whenever the player is healed, just to be consistent.

**Comment by BasilChristofis** [comment]
This IS the generic healing particle, it doesn’t just play on the lifesteal item.

**Comment by LachlanMcCaskill** [comment]
Yeah, I just checked. Sorry Basil. I have an idea for how to change the particle. I'll see what I can do.

**Comment by BasilChristofis** [comment]
No worries

**Review by LachlanMcCaskill — APPROVED** [review]
Have a look again at the changes I've made to the particle. If you're happy, please merge it in.

**Pull request merged**
