### PR TITLE
Room adjustments itchio demo

### PR DESCRIPTION
**Pull request by LachlanMcCaskill**
To Test

- [x]  Play the game enough times so that you see every room that is currently enabled (disable other rooms if you want to guarantee the room you want spawning
- [x]  Ensure that your are happy with the naming convention I have chosen (please discuss)

### CODE REVIEW

**Comment by LachlanMcCaskill** [comment]
I could spend many more hours adding more, but I think I have to stop at some point.

**Comment by JarrydWorland** [comment]
Naming is fine, the level generator is able to handle it and populate the level with those rooms, rooms like RI-NEW may need to be adjusted so it's easy for players to manoeuvrer without being thrown out of the room by the door colliders. There's a few bugs that have already been fixed by other PRs that may improve interactivity by merging in Main as it is now - currently Zappers can chase me out of the room since they don't destroy on Health = 0.  

May also want to make RI-NES more threatening by using one wall between enemies than two

**Comment by LachlanMcCaskill** [comment]
Don't want to change NES right now because I'm not worried about rooms being too easy and I'd rather not place walls in the centre of the room where items will spawn.

**Review by JarrydWorland — APPROVED** [review]
Much easier now to manoeuvre, looks good

**Pull request merged**
