### PR TITLE
Final Cutscene implementation

### PR DESCRIPTION
**Pull request by JarrydWorland**
**Description:** 
That's it Folks, our final cutscene implementation, This has now been integrated into the game and you can go rom the end of the game to cutscene to menu.

Also, I wanted to jazz up the credits, so I've made a new video that replaces the old menu, works like any other cutscene - though if you do have any issues with the video (name/titles) let me know and I can adjust it

**Changes Made:**
- Added New Ending Cutscene and Team Credits Video
- Added new Scenes for new Videos
- Modified Menu behaviour for new Credits Video
- Modified Endgame Script for new Scene
- Adjusted Comments and Code as required

**Testing:** 

- [ ] Opening up Menu and go directly to credits to see the new Credits Video
- [ ] Feel free to cheat through by placing keycards to pick up in the hub, otherwise play through the full game

### CODE REVIEW

**Comment by 102107466** [comment]
Seems good but the letter-boxing is playing up on the new scenes, looking into it now.

**Review by 102113528 — COMMENTED** [review]
I've made some changes to ensure letter boxing is applied to all cutscenes as well as make some dialogue adjustments. Seems alright :+1:, but I would like Andrew's review on this to be sure.

**Review by LachlanMcCaskill — COMMENTED** [review]
I can speak for everything non-code related for this branch. I think it's looking fine. I tested it by placing the keycards in the hub and it all worked as expected. Dialogue lines work naturally. 

I would like a review from someone at SWE because this is an important PR.

**Review by 102107466 — APPROVED** [review]
Looks good

**Pull request merged**
