### PR TITLE
Fix aim direction and input room traversal

### PR DESCRIPTION
**Pull request by BasilChristofis**
This code cancels the disabling of player input upon room transitioning. It does not remove inventory disabling.

### CODE REVIEW

**Comment by BasilChristofis** [comment]
Aim direction bug not fixed yet apparently. Will be doing that over the weekend.

**Comment by 102113528** [comment]
I noticed that there was a side effect to this implementation. You could see movement, look, and shoot inputs being registered in the pause menu. To sovle this, I've changed it so room transitions only disable the time scale, leaving the `GameState.Pause()` and `GameState.Resume()` methods unchanged.

Let me know if this solution still resolves the original issue you had. If so, I'll merge it in.

**Comment by BasilChristofis** [comment]
The alternate solution resolves the issue I was addressing, in a safer way. Feel free to merge it in.

**Comment by 102107466** [comment]
Looks good

**Review by 102107466 — APPROVED** [review]

**Pull request merged**
