### PR TITLE
Door sprite replacement

### PR DESCRIPTION
**Pull request by LachlanMcCaskill**
This branch replaces the closed door sprites with open door sprites
To Test:
- [x] Open any scene with working level generation
- [x] Move through a door

### CODE REVIEW

**Comment by BasilChristofis** [comment]
Looks great!. Can we have the colliders a bit Forward of the door entrances? There seems to be collisions between walls and doors, and Sometimes players can't walk through the doors.

**Comment by BasilChristofis** [comment]
image
This is the issue that I point out, that needs fixing.

**Comment by BasilChristofis** [comment]
On further inspection, it seems to be an issue of minor collider differences between sprites and generation between levels.

**Comment by LachlanMcCaskill** [comment]
> 
> 
> Looks great!. Can we have the colliders a bit Forward of the door entrances? There seems to be collisions between walls and doors, and Sometimes players can't walk through the doors.

@BasilChristofis Do you reckon we should fix it as part of this pull request or do a level cleanup branch later on?

**Comment by BasilChristofis** [comment]
> > Looks great!. Can we have the colliders a bit Forward of the door entrances? There seems to be collisions between walls and doors, and Sometimes players can't walk through the doors.
> 
> @BasilChristofis Do you reckon we should fix it as part of this pull request or do a level cleanup branch later on?

It should be fixed here, as it should just be the door collider sizes. That’s 4 colliders that need to be adjusted.

**Comment by LachlanMcCaskill** [comment]
> 
> 
> On further inspection, it seems to be an issue of minor collider differences between sprites and generation between levels.

Is it only on the room prefabs or is it also on the door prefabs?

**Comment by LachlanMcCaskill** [comment]
@BasilChristofis I pushed some changes to this branch. I think these fix the issue you found.

**Pull request merged**
