### PR TITLE
Added Hold and Stick Dead Zone

### PR DESCRIPTION
**Pull request by BasilChristofis**
ON Navigate in the Input manager for the Input System, I added a Hold interaction, and a   Stick Dead Zone Processor. I was going to manually code in their functionality, until I realised that these options were available.

### CODE REVIEW

**Comment by BasilChristofis** [comment]
Please make sure that you guys are happy with the controls.

**Comment by JarrydWorland** [comment]
Unfortunately, this does break the D pad navigation, where if it's used once, I can't go back to L stick navigation, so I'll have to hold off merging this until that issue can be fixed

**Comment by BasilChristofis** [comment]
I’ll shift over the interaction and processor to joystick specifically then

**Comment by BasilChristofis** [comment]
Shifted Interaction and processor to Gamepad instead of Navigation. Seems to fix the issue. Please check it works on your end.

**Review by JarrydWorland — APPROVED** [review]
Much better! There's a slight chance of bugging it out if you were to brute force the L stick and D pad simultaneously, however this is a very rare instance

**Pull request merged**
