### PR TITLE
Fixed Escape Issue

### PR DESCRIPTION
**Pull request by BasilChristofis**
Got Keybind for escape working. required an else statement in the OnPause Function. Please make sure it works for you guys.

### CODE REVIEW

**Comment by JarrydWorland** [comment]
@BasilChristofis - Just to be clear so I know what you're intending, the escape out of menu only works on the index (initial menu when pausing) rather than at any time on any menu?

**Comment by BasilChristofis** [comment]
Yes that was my idea. I can change it if needed.

**Comment by JarrydWorland** [comment]
No that's all good, just didn't want to pull in something if you were expecting to work in a different way!

**Review by JarrydWorland — APPROVED** [review]
Looks all good, potential to expand this to cover any instance of menu while the game is paused

**Pull request merged**
